# Generated by Django 4.2.9 on 2024-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('target', models.IntegerField(choices=[(0, 'Negative'), (2, 'Neutral'), (4, 'Positive')])),
                ('ids', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('flag', models.CharField(default='NO_QUERY', max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
