# Generated by Django 4.2.9 on 2024-03-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tweet_flag_remove_tweet_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data_id', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('subreddit', models.CharField(max_length=255)),
                ('link_id', models.CharField(max_length=255)),
                ('parent_id', models.CharField(max_length=255)),
                ('created_utc', models.CharField(max_length=255)),
                ('rater_id', models.CharField(max_length=255)),
                ('example_very_unclear', models.BooleanField(default=False)),
                ('admiration', models.BooleanField(default=False)),
                ('amusement', models.BooleanField(default=False)),
                ('anger', models.BooleanField(default=False)),
                ('annoyance', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
                ('caring', models.BooleanField(default=False)),
                ('confusion', models.BooleanField(default=False)),
                ('curiosity', models.BooleanField(default=False)),
                ('desire', models.BooleanField(default=False)),
                ('disappointment', models.BooleanField(default=False)),
                ('disapproval', models.BooleanField(default=False)),
                ('disgust', models.BooleanField(default=False)),
                ('embarrassment', models.BooleanField(default=False)),
                ('excitement', models.BooleanField(default=False)),
                ('fear', models.BooleanField(default=False)),
                ('gratitude', models.BooleanField(default=False)),
                ('grief', models.BooleanField(default=False)),
                ('joy', models.BooleanField(default=False)),
                ('love', models.BooleanField(default=False)),
                ('nervousness', models.BooleanField(default=False)),
                ('optimism', models.BooleanField(default=False)),
                ('pride', models.BooleanField(default=False)),
                ('realization', models.BooleanField(default=False)),
                ('relief', models.BooleanField(default=False)),
                ('remorse', models.BooleanField(default=False)),
                ('sadness', models.BooleanField(default=False)),
                ('surprise', models.BooleanField(default=False)),
                ('neutral', models.BooleanField(default=False)),
            ],
        ),
    ]
