# Generated by Django 4.2.9 on 2024-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_goemotion_id_alter_goemotion_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255)),
                ('original_text', models.TextField()),
                ('predicted_sentiment', models.CharField(max_length=50)),
                ('user_corrected_sentiment', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
