# Generated by Django 4.2.9 on 2024-04-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sentimentfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentfeedback',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='sentimentfeedback',
            name='tweet_id',
        ),
        migrations.AddField(
            model_name='sentimentfeedback',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tweet'),
        ),
    ]
